const shopActiontype = {
  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FALUIR: "FETCH_COLLECTIONS_FALUIR"
};

export default shopActiontype;
